/*! Modula-2 R10 Compiler (m2r10c)
 *
 *  @file  m2_table_of_productions.h
 *  @brief Master table of EBNF productions
 *
 *  @attention
 *  The data in this file is generated by gen_first_and_follow_sets.c
 *
 *  @b Copyright: (C) 2010 B.Kowarsch. All rights reserved.
 *
 *  @b License:
 *
 *  Permission is hereby granted to review and test this software for the sole
 *  purpose of supporting the effort by the licensor  to implement a reference
 *  compiler for  Modula-2 R10.  It is not permissible under any circumstances
 *  to  use the software  for the purpose  of creating derivative languages or 
 *  dialects.  This permission is valid until 31 December 2010, 24:00h GMT.
 *
 *  Future licensing:
 *
 *  The licensor undertakes  to release  this software  under a BSD-style open
 *  source license  AFTER  the M2R10 language definition has been finalised.
 *  
 */

// This  file  represents  the  EBNF PRODUCTION MASTER TABLE   for  the  M2R10
// compiler, used to generate data structures containing productions and their
// FIRST and FOLLOW sets, thereby keeping those structures in synchronisation.
// Consequently,  any changes,  additions or removals of productions and their
// respective FIRST and FOLLOW sets must be made in  this  file,  not anywhere
// else.  Failing to do so  will  result in an incorrect compiler  as  related
// data structures will no longer be synchronised.
//
// NB:  The  FIRST and FOLLOW set data  in this file  has  been  automatically
// generated using the utility gen_first_and_follow_sets.c
//
//
// How to use this master table:
//
// The  following  code  will  generate  a declaration  for  an enumeration of
// all productions prefixed with p_ ...
//
//  #define _add_production(_production, \
//      _first0,  _first1,  _first2, \
//      _follow0, _follow1, _follow2 ) p_ ## _production,
//
//  typedef enum m2_production_t {
//  #include "m2_table_of_productions.h"
//  M2_NUMBER_OF_PRODUCTIONS
//  } /* m2_production_t */;
//  #undef _add_production
//
//
// The following code will generate an array of tokensets initialised with the
// FIRST sets of all productions ...
//
//  #define _add_production(_production, \
//      _first0,  _first1,  _first2, \
//      _follow0, _follow1, _follow2 ) \
//      { _first0, _first1, _first2 },
//
//  m2_tokenset_a FIRST[] = {
//  #include "m2_table_of_productions.h"
//  { 0, 0, 0 }
//  } /* FIRST */;
//  #undef _add_production
//
//
// The following code will generate an array of tokensets initialised with the
// FOLLOW sets of all productions ...
//
//  #define _add_production(_production, \
//      _first0,  _first1,  _first2, \
//      _follow0, _follow1, _follow2 ) \
//      { _follow0, _follow1, _follow2 },
//
//  m2_tokenset_a FOLLOW[] = {
//  #include "m2_table_of_productions.h"
//  { 0, 0, 0 }
//  } /* FOLLOW */;
//  #undef _add_production
//
//
// Arguments for the _add_production macro:
//
//  1st: production name, must be preceeded by an underscore
//
//  2nd: 32-bit unsigned integer representing bits  0 to  31 of FIRST set
//  3rd: 32-bit unsigned integer representing bits 32 to  63 of FIRST set
//  4th: 32-bit unsigned integer representing bits 64 to  95 of FIRST set
//
//  5th: 32-bit unsigned integer representing bits  0 to  31 of FOLLOW set
//  6th: 32-bit unsigned integer representing bits 32 to  63 of FOLLOW set
//  7th: 32-bit unsigned integer representing bits 64 to  95 of FOLLOW set


// Productions

// #1
_add_production( _compilation_unit,
                0x04200400, 0x00000002, 0x00000000,   // FIRST set
                0x00000000, 0x00000000, 0x00010000 )  // FOLLOW set

// #2
_add_production( _prototype,
                0x00000000, 0x00000002, 0x00000000,   // FIRST set
                0x00000000, 0x00000000, 0x00010000 )  // FOLLOW set

// #3
_add_production( _program_module,
                0x04000000, 0x00000000, 0x00000000,   // FIRST set
                0x00000000, 0x00000000, 0x00010000 )  // FOLLOW set

// #4
_add_production( _definition_of_module,
                0x00000400, 0x00000000, 0x00000000,   // FIRST set
                0x00000000, 0x00000000, 0x00010000 )  // FOLLOW set

// #5
_add_production( _implementation_of_module,
                0x00200000, 0x00000000, 0x00000000,   // FIRST set
                0x00000000, 0x00000000, 0x00010000 )  // FOLLOW set

// #6
_add_production( _required_binding,
                0x00000000, 0x00000001, 0x00000000,   // FIRST set
                0x00010200, 0x00000001, 0x00000000 )  // FOLLOW set

// #7
_add_production( _bindable_operator,
                0x02841000, 0x52260000, 0x00003803,   // FIRST set
                0x00000000, 0x00000000, 0x00000100 )  // FOLLOW set

// #8
_add_production( _import_list,
                0x00480000, 0x00000000, 0x00000000,   // FIRST set
                0x00010220, 0x00000501, 0x00000000 )  // FOLLOW set

// #9
_add_production( _block,
                0x00000220, 0x00000501, 0x00000000,   // FIRST set
                0x00000000, 0x00002000, 0x00000000 )  // FOLLOW set

// #10
_add_production( _declaration,
                0x00000200, 0x00000501, 0x00000000,   // FIRST set
                0x00010020, 0x00000000, 0x00000000 )  // FOLLOW set

// #11
_add_production( _definition,
                0x00000200, 0x00000501, 0x00000000,   // FIRST set
                0x00010000, 0x00000000, 0x00000000 )  // FOLLOW set

// #12
_add_production( _const_declaration,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #13
_add_production( _type,
                0x8000001A, 0x00002025, 0x000000A0,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #14
_add_production( _range,
                0x00000000, 0x00000000, 0x00000080,   // FIRST set
                0x10000000, 0x00000000, 0x00000000 )  // FOLLOW set

// #15
_add_production( _enumeration_type,
                0x00000000, 0x00000000, 0x00000020,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #16
_add_production( _array_type,
                0x00000018, 0x00000000, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #17
_add_production( _record_type,
                0x00000000, 0x00000004, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #18
_add_production( _field_list_sequence,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x00010000, 0x00000000, 0x00000000 )  // FOLLOW set

// #19
_add_production( _field_list,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x00010000, 0x20000000, 0x00000000 )  // FOLLOW set

// #20
_add_production( _set_type,
                0x00000000, 0x00000020, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #21
_add_production( _pointer_type,
                0x80000000, 0x00000000, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #22
_add_production( _procedure_type,
                0x00000000, 0x00000001, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #23
_add_production( _formal_type_list,
                0x00000308, 0x00002C00, 0x00000000,   // FIRST set
                0x00000000, 0x24000000, 0x00000000 )  // FOLLOW set

// #24
_add_production( _formal_type,
                0x00000308, 0x00002C00, 0x00000000,   // FIRST set
                0x00000000, 0x24100000, 0x00000000 )  // FOLLOW set

// #25
_add_production( _attributed_formal_type,
                0x00000308, 0x00002400, 0x00000000,   // FIRST set
                0x00000000, 0x24100000, 0x00000000 )  // FOLLOW set

// #26
_add_production( _simple_formal_type,
                0x00000108, 0x00002000, 0x00000000,   // FIRST set
                0x00000000, 0x24100000, 0x00000000 )  // FOLLOW set

// #27
_add_production( _variadic_formal_type,
                0x00000000, 0x00000800, 0x00000000,   // FIRST set
                0x00000000, 0x24100000, 0x00000000 )  // FOLLOW set

// #28
_add_production( _variable_declaration,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #29
_add_production( _procedure_declaration,
                0x00000000, 0x00000001, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #30
_add_production( _procedure_header,
                0x00000000, 0x00000001, 0x00000000,   // FIRST set
                0x00000000, 0x20000000, 0x00000000 )  // FOLLOW set

// #31
_add_production( _formal_param_list,
                0x00000200, 0x00002C00, 0x00000000,   // FIRST set
                0x00000000, 0x00000000, 0x00000040 )  // FOLLOW set

// #32
_add_production( _formal_params,
                0x00000200, 0x00002C00, 0x00000000,   // FIRST set
                0x00000000, 0x20000800, 0x00000040 )  // FOLLOW set

// #33
_add_production( _simple_formal_params,
                0x00000000, 0x00000800, 0x00000000,   // FIRST set
                0x00000000, 0x20000800, 0x00000040 )  // FOLLOW set

// #34
_add_production( _variadic_formal_params,
                0x00000200, 0x00002400, 0x00000000,   // FIRST set
                0x00000000, 0x20000800, 0x00000040 )  // FOLLOW set

// #35
_add_production( _statement,
                0x01160080, 0x00003018, 0x00000000,   // FIRST set
                0x00014000, 0x20000200, 0x00000010 )  // FOLLOW set

// #36
_add_production( _statement_sequence,
                0x01160080, 0x00003018, 0x00000000,   // FIRST set
                0x0001C000, 0x00000200, 0x00000010 )  // FOLLOW set

// #37
_add_production( _assignment_or_procedure_call,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x00014000, 0x20000200, 0x00000010 )  // FOLLOW set

// #38
_add_production( _if_statement,
                0x00100000, 0x00000000, 0x00000000,   // FIRST set
                0x00014000, 0x20000200, 0x00000010 )  // FOLLOW set

// #39
_add_production( _case_statement,
                0x00000080, 0x00000000, 0x00000000,   // FIRST set
                0x00014000, 0x20000200, 0x00000010 )  // FOLLOW set

// #40
_add_production( _case,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x00014000, 0x00000000, 0x00000010 )  // FOLLOW set

// #41
_add_production( _case_labels,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x00000000, 0x04100000, 0x00000000 )  // FOLLOW set

// #42
_add_production( _while_statement,
                0x00000000, 0x00001000, 0x00000000,   // FIRST set
                0x00014000, 0x20000200, 0x00000010 )  // FOLLOW set

// #43
_add_production( _repeat_statement,
                0x00000000, 0x00000008, 0x00000000,   // FIRST set
                0x00014000, 0x20000200, 0x00000010 )  // FOLLOW set

// #44
_add_production( _loop_statement,
                0x01000000, 0x00000000, 0x00000000,   // FIRST set
                0x00014000, 0x20000200, 0x00000010 )  // FOLLOW set

// #45
_add_production( _for_statement,
                0x00040000, 0x00000000, 0x00000000,   // FIRST set
                0x00014000, 0x20000200, 0x00000010 )  // FOLLOW set

// #46
_add_production( _const_expression,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x10002040, 0x25100000, 0x00000740 )  // FOLLOW set

// #47
_add_production( _relation,
                0x00800000, 0xC0010000, 0x00000007,   // FIRST set
                0x08000000, 0x0024E000, 0x00000020 )  // FOLLOW set

// #48
_add_production( _simple_const_expr,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x00800000, 0xC8010000, 0x00000007 )  // FOLLOW set

// #49
_add_production( _add_operator,
                0x40000000, 0x00240000, 0x00000000,   // FIRST set
                0x08000000, 0x0000E000, 0x00000020 )  // FOLLOW set

// #50
_add_production( _const_term,
                0x08000100, 0x0000E000, 0x00000220,   // FIRST set
                0x40800000, 0xC8250000, 0x00000007 )  // FOLLOW set

// #51
_add_production( _mul_operator,
                0x02001004, 0x02020000, 0x00000000,   // FIRST set
                0x08000000, 0x0000E000, 0x00000020 )  // FOLLOW set

// #52
_add_production( _const_factor,
                0x08000100, 0x0000E000, 0x00000220,   // FIRST set
                0x42801004, 0xCA270000, 0x00000007 )  // FOLLOW set

// #53
_add_production( _designator,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x00010000, 0x30480000, 0x00000020 )  // FOLLOW set

// #54
_add_production( _designator_tail,
                0x00000000, 0x00000000, 0x00000088,   // FIRST set
                0x00010000, 0x30480000, 0x00000020 )  // FOLLOW set

// #55
_add_production( _expression_list,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x00000000, 0x00000000, 0x00000140 )  // FOLLOW set

// #56
_add_production( _expression,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x1001E000, 0x201002C0, 0x00000150 )  // FOLLOW set

// #57
_add_production( _simple_expression,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x1801E000, 0x2834E2C0, 0x00000150 )  // FOLLOW set

// #58
_add_production( _term,
                0x08000100, 0x0000E000, 0x00000220,   // FIRST set
                0x5801E000, 0x2834E2C0, 0x00000150 )  // FOLLOW set

// #59
_add_production( _factor,
                0x08000100, 0x0000E000, 0x00000220,   // FIRST set
                0x5801E000, 0x2834E2C0, 0x00000150 )  // FOLLOW set

// #60
_add_production( _designator_or_procedure_call,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x5801E000, 0x2834E2C0, 0x00000150 )  // FOLLOW set

// #61
_add_production( _actual_parameters,
                0x00000000, 0x00000000, 0x00000020,   // FIRST set
                0x5801E000, 0x2834E2C0, 0x00000150 )  // FOLLOW set

// #62
_add_production( _const_structured_value,
                0x00000000, 0x00000000, 0x00000200,   // FIRST set
                0x00014000, 0x20100200, 0x00000410 )  // FOLLOW set

// #63
_add_production( _const_value_component,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x00000000, 0x00100000, 0x00000400 )  // FOLLOW set

// #64
_add_production( _structured_value,
                0x00000000, 0x00000000, 0x00000200,   // FIRST set
                0x00014000, 0x20100200, 0x00000410 )  // FOLLOW set

// #65
_add_production( _value_component,
                0x08000100, 0x0024E000, 0x00000220,   // FIRST set
                0x00000000, 0x00100000, 0x00000400 )  // FOLLOW set

// #66
_add_production( _qualident,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x5281F004, 0xFA7F02C0, 0x000001FF )  // FOLLOW set

// #67
_add_production( _ident_list,
                0x00000000, 0x00002000, 0x00000000,   // FIRST set
                0x00010000, 0x24000000, 0x00000040 )  // FOLLOW set

// END OF FILE
